name: codespell
on:
  push:
  #  branches: [ master ]
  pull_request:
  #  branches: [ master ]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: codespell --ignore-words-list="crate,dependees,dne,fpr,ony,nin,nwe,ser,spawnve,tey"
          --quiet-level=2 --skip="*/all_the_henries,*/CONTRIBUTORS.md"
